Class {
	#name : #HighstockPlotOptionsMfiDataLabelsTextPathTest,
	#superclass : #TestCase,
	#category : #'HighstockSt-V8-Tests'
}

{ #category : #'tests-accessing' }
HighstockPlotOptionsMfiDataLabelsTextPathTest >> testAttributes [

	| component javascript expectedConfiguration |

	component := HighstockPlotOptionsMfiDataLabelsTextPath new.
	component attributes: 'test'.
	javascript := String streamContents: [ :stream | component javascriptContentOn: stream ].
	expectedConfiguration := Dictionary new
		at: 'attributes' put: 'test';
		yourself.
	self assert: javascript equals: expectedConfiguration asJavascript
]

{ #category : #'tests-accessing' }
HighstockPlotOptionsMfiDataLabelsTextPathTest >> testEnabled [

	| component javascript expectedConfiguration |

	component := HighstockPlotOptionsMfiDataLabelsTextPath new.
	component enabled: 'test'.
	javascript := String streamContents: [ :stream | component javascriptContentOn: stream ].
	expectedConfiguration := Dictionary new
		at: 'enabled' put: 'test';
		yourself.
	self assert: javascript equals: expectedConfiguration asJavascript
]
