Class {
	#name : #HighstockAnnotationsPitchforkControlPointOptionsStyleTest,
	#superclass : #TestCase,
	#category : #'HighstockSt-V7-Tests'
}

{ #category : #'tests-accessing' }
HighstockAnnotationsPitchforkControlPointOptionsStyleTest >> testFill [

	| component javascript expectedConfiguration |

	component := HighstockAnnotationsPitchforkControlPointOptionsStyle new.
	component fill: 'test'.
	javascript := String streamContents: [ :stream | component javascriptContentOn: stream ].
	expectedConfiguration := Dictionary new
		at: 'fill' put: 'test';
		yourself.
	self assert: javascript equals: expectedConfiguration asJavascript
]

{ #category : #'tests-accessing' }
HighstockAnnotationsPitchforkControlPointOptionsStyleTest >> testStroke [

	| component javascript expectedConfiguration |

	component := HighstockAnnotationsPitchforkControlPointOptionsStyle new.
	component stroke: 'test'.
	javascript := String streamContents: [ :stream | component javascriptContentOn: stream ].
	expectedConfiguration := Dictionary new
		at: 'stroke' put: 'test';
		yourself.
	self assert: javascript equals: expectedConfiguration asJavascript
]

{ #category : #'tests-accessing' }
HighstockAnnotationsPitchforkControlPointOptionsStyleTest >> testWidth [

	| component javascript expectedConfiguration |

	component := HighstockAnnotationsPitchforkControlPointOptionsStyle new.
	component width: 'test'.
	javascript := String streamContents: [ :stream | component javascriptContentOn: stream ].
	expectedConfiguration := Dictionary new
		at: 'width' put: 'test';
		yourself.
	self assert: javascript equals: expectedConfiguration asJavascript
]
