Class {
	#name : #HighstockNavigationBindingsFullScreenTest,
	#superclass : #TestCase,
	#category : #'HighstockSt-V7-Tests'
}

{ #category : #'tests-accessing' }
HighstockNavigationBindingsFullScreenTest >> testInit [

	| component javascript expectedConfiguration |

	component := HighstockNavigationBindingsFullScreen new.
	component init: 'test'.
	javascript := String streamContents: [ :stream | component javascriptContentOn: stream ].
	expectedConfiguration := Dictionary new
		at: 'init' put: 'test';
		yourself.
	self assert: javascript equals: expectedConfiguration asJavascript
]
