Class {
	#name : #HighstockSeriesAreasplinerangeDataDataLabelsFilterTest,
	#superclass : #TestCase,
	#category : #'HighstockSt-V7-Tests'
}

{ #category : #'tests-accessing' }
HighstockSeriesAreasplinerangeDataDataLabelsFilterTest >> testOperator [

	| component javascript expectedConfiguration |

	component := HighstockSeriesAreasplinerangeDataDataLabelsFilter new.
	component operator: 'test'.
	javascript := String streamContents: [ :stream | component javascriptContentOn: stream ].
	expectedConfiguration := Dictionary new
		at: 'operator' put: 'test';
		yourself.
	self assert: javascript equals: expectedConfiguration asJavascript
]

{ #category : #'tests-accessing' }
HighstockSeriesAreasplinerangeDataDataLabelsFilterTest >> testProperty [

	| component javascript expectedConfiguration |

	component := HighstockSeriesAreasplinerangeDataDataLabelsFilter new.
	component property: 'test'.
	javascript := String streamContents: [ :stream | component javascriptContentOn: stream ].
	expectedConfiguration := Dictionary new
		at: 'property' put: 'test';
		yourself.
	self assert: javascript equals: expectedConfiguration asJavascript
]

{ #category : #'tests-accessing' }
HighstockSeriesAreasplinerangeDataDataLabelsFilterTest >> testValue [

	| component javascript expectedConfiguration |

	component := HighstockSeriesAreasplinerangeDataDataLabelsFilter new.
	component value: 'test'.
	javascript := String streamContents: [ :stream | component javascriptContentOn: stream ].
	expectedConfiguration := Dictionary new
		at: 'value' put: 'test';
		yourself.
	self assert: javascript equals: expectedConfiguration asJavascript
]
