Class {
	#name : #HighstockSeriesWindbarbStatesTest,
	#superclass : #TestCase,
	#category : #'HighstockSt-V8-Series-Windbarb-Tests'
}

{ #category : #'tests-accessing' }
HighstockSeriesWindbarbStatesTest >> testGetHover [

	| component javascript expectedConfiguration |

	component := HighstockSeriesWindbarbStates new.
	component hover.
	javascript := String streamContents: [ :stream | component javascriptContentOn: stream ].
	expectedConfiguration := Dictionary new
		at: 'hover' put: Dictionary new;
		yourself.
	self assert: javascript equals: expectedConfiguration asJavascript
]

{ #category : #'tests-accessing' }
HighstockSeriesWindbarbStatesTest >> testGetInactive [

	| component javascript expectedConfiguration |

	component := HighstockSeriesWindbarbStates new.
	component inactive.
	javascript := String streamContents: [ :stream | component javascriptContentOn: stream ].
	expectedConfiguration := Dictionary new
		at: 'inactive' put: Dictionary new;
		yourself.
	self assert: javascript equals: expectedConfiguration asJavascript
]

{ #category : #'tests-accessing' }
HighstockSeriesWindbarbStatesTest >> testGetNormal [

	| component javascript expectedConfiguration |

	component := HighstockSeriesWindbarbStates new.
	component normal.
	javascript := String streamContents: [ :stream | component javascriptContentOn: stream ].
	expectedConfiguration := Dictionary new
		at: 'normal' put: Dictionary new;
		yourself.
	self assert: javascript equals: expectedConfiguration asJavascript
]

{ #category : #'tests-accessing' }
HighstockSeriesWindbarbStatesTest >> testGetSelect [

	| component javascript expectedConfiguration |

	component := HighstockSeriesWindbarbStates new.
	component select.
	javascript := String streamContents: [ :stream | component javascriptContentOn: stream ].
	expectedConfiguration := Dictionary new
		at: 'select' put: Dictionary new;
		yourself.
	self assert: javascript equals: expectedConfiguration asJavascript
]
