Class {
	#name : #HighstockSeriesStochasticSmoothedLineStylesTest,
	#superclass : #TestCase,
	#category : 'HighstockStV6-Tests'
}

{ #category : #'tests-accessing' }
HighstockSeriesStochasticSmoothedLineStylesTest >> testLineColor [

	| component javascript expectedConfiguration |

	component := HighstockSeriesStochasticSmoothedLineStyles new.
	component lineColor: 'test'.
	javascript := String streamContents: [ :stream | component javascriptContentOn: stream ].
	expectedConfiguration := Dictionary new
		at: 'lineColor' put: 'test';
		yourself.
	self assert: javascript equals: expectedConfiguration asJavascript
]

{ #category : #'tests-accessing' }
HighstockSeriesStochasticSmoothedLineStylesTest >> testLineWidth [

	| component javascript expectedConfiguration |

	component := HighstockSeriesStochasticSmoothedLineStyles new.
	component lineWidth: 'test'.
	javascript := String streamContents: [ :stream | component javascriptContentOn: stream ].
	expectedConfiguration := Dictionary new
		at: 'lineWidth' put: 'test';
		yourself.
	self assert: javascript equals: expectedConfiguration asJavascript
]
