Class {
	#name : #HighstockSeriesSplineIkhPointTest,
	#superclass : #TestCase,
	#category : 'HighstockStV6-Tests'
}

{ #category : #'tests-accessing' }
HighstockSeriesSplineIkhPointTest >> testEvents [

	| component javascript expectedConfiguration |

	component := HighstockSeriesSplineIkhPoint new.
	component events: 'test'.
	javascript := String streamContents: [ :stream | component javascriptContentOn: stream ].
	expectedConfiguration := Dictionary new
		at: 'events' put: 'test';
		yourself.
	self assert: javascript equals: expectedConfiguration asJavascript
]
