tests-accessing
testDescription

	| component javascript expectedConfiguration |

	component := HighchartsSeriesAreasplinerangeData new.
	component description: 'test'.
	javascript := String streamContents: [ :stream | component javascriptContentOn: stream ].
	expectedConfiguration := Dictionary new
		at: 'description' put: 'test';
		yourself.
	self assert: javascript equals: expectedConfiguration asJavascript