Class {
	#name : #HighchartsSeriesPyramid3dStatesSelectAnimationTest,
	#superclass : #TestCase,
	#category : #'HighchartsSt-V7-Tests'
}

{ #category : #'tests-accessing' }
HighchartsSeriesPyramid3dStatesSelectAnimationTest >> testDuration [

	| component javascript expectedConfiguration |

	component := HighchartsSeriesPyramid3dStatesSelectAnimation new.
	component duration: 'test'.
	javascript := String streamContents: [ :stream | component javascriptContentOn: stream ].
	expectedConfiguration := Dictionary new
		at: 'duration' put: 'test';
		yourself.
	self assert: javascript equals: expectedConfiguration asJavascript
]
