Class {
	#name : #HighchartsSeriesBarDataAccessibilityTest,
	#superclass : #TestCase,
	#category : #'HighchartsSt-V7-Tests'
}

{ #category : #'tests-accessing' }
HighchartsSeriesBarDataAccessibilityTest >> testDescription [

	| component javascript expectedConfiguration |

	component := HighchartsSeriesBarDataAccessibility new.
	component description: 'test'.
	javascript := String streamContents: [ :stream | component javascriptContentOn: stream ].
	expectedConfiguration := Dictionary new
		at: 'description' put: 'test';
		yourself.
	self assert: javascript equals: expectedConfiguration asJavascript
]
