Class {
	#name : #HighchartsSeriesBarDataSortingTest,
	#superclass : #TestCase,
	#category : #'HighchartsSt-V8-Series-Bar-Tests'
}

{ #category : #'tests-accessing' }
HighchartsSeriesBarDataSortingTest >> testSetEnabled [

	| component javascript expectedConfiguration |

	component := HighchartsSeriesBarDataSorting new.
	component enabled: 'test'.
	javascript := String streamContents: [ :stream | component javascriptContentOn: stream ].
	expectedConfiguration := Dictionary new
		at: 'enabled' put: 'test';
		yourself.
	self assert: javascript equals: expectedConfiguration asJavascript
]

{ #category : #'tests-accessing' }
HighchartsSeriesBarDataSortingTest >> testSetMatchByName [

	| component javascript expectedConfiguration |

	component := HighchartsSeriesBarDataSorting new.
	component matchByName: 'test'.
	javascript := String streamContents: [ :stream | component javascriptContentOn: stream ].
	expectedConfiguration := Dictionary new
		at: 'matchByName' put: 'test';
		yourself.
	self assert: javascript equals: expectedConfiguration asJavascript
]

{ #category : #'tests-accessing' }
HighchartsSeriesBarDataSortingTest >> testSetSortKey [

	| component javascript expectedConfiguration |

	component := HighchartsSeriesBarDataSorting new.
	component sortKey: 'test'.
	javascript := String streamContents: [ :stream | component javascriptContentOn: stream ].
	expectedConfiguration := Dictionary new
		at: 'sortKey' put: 'test';
		yourself.
	self assert: javascript equals: expectedConfiguration asJavascript
]
