Class {
	#name : #HighchartsSeriesNetworkgraphMarkerStatesInactiveTest,
	#superclass : #TestCase,
	#category : #'HighchartsSt-V8-Tests'
}

{ #category : #'tests-accessing' }
HighchartsSeriesNetworkgraphMarkerStatesInactiveTest >> testGetAnimation [

	| component javascript expectedConfiguration |

	component := HighchartsSeriesNetworkgraphMarkerStatesInactive new.
	component animation.
	javascript := String streamContents: [ :stream | component javascriptContentOn: stream ].
	expectedConfiguration := Dictionary new
		at: 'animation' put: Dictionary new;
		yourself.
	self assert: javascript equals: expectedConfiguration asJavascript
]

{ #category : #'tests-accessing' }
HighchartsSeriesNetworkgraphMarkerStatesInactiveTest >> testSetOpacity [

	| component javascript expectedConfiguration |

	component := HighchartsSeriesNetworkgraphMarkerStatesInactive new.
	component opacity: 'test'.
	javascript := String streamContents: [ :stream | component javascriptContentOn: stream ].
	expectedConfiguration := Dictionary new
		at: 'opacity' put: 'test';
		yourself.
	self assert: javascript equals: expectedConfiguration asJavascript
]
