tests-accessing
testFooterFormat

	| component javascript expectedConfiguration |

	component := HighstockSeriesColumnrangeIkhTooltip new.
	component footerFormat: 'test'.
	javascript := String streamContents: [ :stream | component javascriptContentOn: stream ].
	expectedConfiguration := Dictionary new
		at: 'footerFormat' put: 'test';
		yourself.
	self assert: javascript equals: expectedConfiguration asJavascript