name: Build

on: [push,pull_request]

jobs:
   build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        smalltalk: [ Pharo64-8.0, Pharo64-7.0, Pharo32-7.0, Pharo32-6.1 ]
    name: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@v2
      - uses: ba-st-actions/setup-smalltalkCI@v1.0.0
        with:
          smalltalk-version: ${{ matrix.smalltalk }}
      - run: smalltalkci -s ${{ matrix.smalltalk }}
        timeout-minutes: 60
        env:
          SMALLTALK_CI_TIMEOUT: 50
      - run: echo "::set-env name=SCI_COVERAGE_FILE_LOCATION::${HOME}/.smalltalkCI/_builds/coveralls_results.json"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ${{ env.SCI_COVERAGE_FILE_LOCATION }}
